### ISSUE TITLE
Data missing for entry `54X VAL` in spice 2.0.1

### ISSUE THREAD

**Issue by leifjacobson** [openmm/spice-dataset#106]
Downloaded spice 2.0.1 from zenodo and found one entry that appears to be missing data.  conformations, dft_energy, etc. all report the shape to be zero.  It does have a smiles string though.

**Comment by peastman** [comment]
That's correct.  It's a dimer from the ligand / amino acid subset.  There was only one conformation for it to begin with, and that conformation was excluded because the forces were too large.

**Comment by leifjacobson** [comment]
OK, no problem, just reporting for your own knowledge in case it was a mistake.  Thanks for sharing the nice dataset, please close this issue if needed.
