### ISSUE TITLE
SPICE Amino Acid Ligand v1.0 54X VAL has no coordinates

### ISSUE THREAD

**Issue by JSLJ23** [openmm/spice-dataset#111]
While trying to extract the conformations of molecules from the Amino Acid Ligand subset for training, I found that 54X_VAL has empty coordinates. Is this expected?

```python
import h5py

with h5py.File("./SPICE-2.0.1.hdf5", "r") as f:
    for key, val in f.items():
        molecule_name = key.replace(" ", "_")
        if molecule_name == "54X_VAL":
            coordinates = val["conformations"][:]
            print(coordinates.shape)
```
> (0,)

**Comment by peastman** [comment]
Yes, that's an artifact of how the downloader script is written.  There was only one conformation for that dimer, and it was excluded due to a force being above the cutoff, leaving a record with no conformations at all.
