### ISSUE TITLE
Steps to reproduce D3 contribution for each structure

### ISSUE THREAD

**Issue by YutackPark** [openmm/spice-dataset#113]
I want to subtract D3 contribution from each structure, to train machine learning potentials.

In this purpose, could you share D3 related parameters used in SPICE dataset?

It would be very helpful for users interested in training interatomic potentials with the SPICE dataset. 
Although potentials can be directly trained with D3 combined results, it is more reliable to train on data without D3 contribution and add D3 explicitly in model inference.

**Comment by peastman** [comment]
The original datasets on QCArchive contain a lot more fields than what we included in the HDF5 file.  If you want others, you can run [the downloader script](https://github.com/openmm/spice-dataset/tree/main/downloader) yourself, first editing the config file to tell it what fields to store.  See [the Psi4 documentation](https://psicode.org/psi4manual/master/glossary_psivariables.html) for descriptions of the fields.  The ones you're probably interested in are `'dft functional total energy'` (the energy without the dispersion correction) and `'dispersion correction energy'`.

Be aware that downloading from QCArchive is very slow!  Expect it to take about a day to download the whole dataset.

**Comment by peastman** [comment]
Also `'dispersion correction gradient'` if you want the forces.

**Comment by YutackPark** [comment]
Thank you for the detailed instructions. It works perfectly!
