### ISSUE TITLE
Availability of Psi4 wavefunction objects for ωB97M-D3BJ/def2-TZVPPD calculations

### ISSUE THREAD

**Issue by JSLJ23** [openmm/spice-dataset#115]
Hi SPICE authors,

I was wondering if the Psi4 wavefunction objects for the ωB97M-D3BJ/def2-TZVPPD calculations might have been saved from the Psi4 runs?
I was hoping to use them to obtain other QM related properties for the molecules like density fitting basis function coefficients for a model that learns to predict those.

**Comment by peastman** [comment]
Unfortunately no.  The very first dataset we submitted saved wavefunctions, and we got a panicked message from QCArchive that we were filling up all their storage at a ridiculous rate.  So we turned off storing wavefunctions on all other datasets.

**Comment by JSLJ23** [comment]
Ahh ok, makes sense.
