### ISSUE TITLE
Release of GFN2-xTB data?

### ISSUE THREAD

**Issue by sarmaier** [openmm/spice-dataset#117]
Hello! Thank you so much for your dataset! I recently saw this package [https://www.openqdc.io/datasets/spice_vl2](url) and wondered if you had any plans to put out GFN2-xTB data for SpiceV2 yourself?

**Comment by peastman** [comment]
No plans to do it.  GFN2-xTB is *really* cheap to compute.  If you want to compute it yourself, it will probably only take a few hours.
