### ISSUE TITLE
 What molecules to include in version 2 (tripeptides)

### ISSUE THREAD

**Issue by cing** [openmm/spice-dataset#12]
No disagreement on the current priorities described in #1 , but of the many options available to include in version 2, I would be interested to see additions to dataset towards larger solvated peptide fragments.

RMSD-based clustering of high-temperature trajectories on gas-phase peptides was [performed here](https://github.com/openmm/qmdataset/blob/main/dipeptides/createDipeptides.py), and I expect solution-phase peptides will also be generated using a similar protocol. In principle, I have no issues using this procedure for larger peptides, but I'll mention here that I've completed explicit solvent MD of a combinatorial set of capped tripeptides with the intent to build a QM dataset like this initiative and can contribute a subset of RMSD-clustered conformations to this project if desired (which would require QM calculations).

Specifically, I've run OpenMM for explicit solvent replica exchange with solute tempering (REST) on over 10,000 unique capped tripeptides of form: (Ac-**X**-**Y**-**Z**-NH2) using AMBER15-IPQ. Here **X** and **Z** are the standard twenty amino acids "ACDEFGHIKLMNPQRSTVWY", and **Y** is a slightly larger set of those and "ASH,GLH,NLE,HID,HIP,AIB,B3A,B3G,B3P,BCY,APC,B3D" ([non-canonical amino acid parameterization here](https://aip.scitation.org/doi/abs/10.1063/5.0019054)). 

I do not know is if tripeptides offer diminishing returns over dipeptides for a forcefield development, and I appreciate high chemical diversity may be the primary focus of this dataset. I will say there may be benefits to having preferred rotamer and solvation structure at sampled extensively 300K.

**Comment by cing** [comment]
My read is that this dataset proposal is not consistent with the highest priority needs of SPICE for v2

**Comment by jchodera** [comment]
I think #67 is trying to collect ideas in one place!
