### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by peastman** [openmm/spice-dataset#14]
The name `qmdataset` was just intended as a placeholder.  Now that we have a name, shall I rename this repository to `spice`?

**Comment by jchodera** [comment]
How about `spice-qmdataset` so that it's clear and searchable?

**Comment by peastman** [comment]
That could work.  Or maybe just `spice-dataset`?

**Comment by jchodera** [comment]
![image](https://user-images.githubusercontent.com/3656088/148626676-570fab31-7c0c-4e4e-ab31-4f5d1bb4c19e.png)

Is there another way to make it a bit more unique?

**Comment by peastman** [comment]
We're just talking about the name of this github repository.  It just needs to be accurate and easy to remember.  It doesn't need to be unique and easily searchable all on its own.  Web searches aren't solely based on a repo name.

**Comment by jchodera** [comment]
True, but if we give the repo a unique name, we don't have to do extensive search engine optimization of the rest of the contents. It makes things much easier.

Something like `openmm-spice-qmdataset` makes it super easy to find, especially if we call it in words "the OpenMM Spice QM Dataset".

**Comment by peastman** [comment]
"openmm" is already part of the name, since it's the organization.  I don't want to overemphasize that, though.  The dataset isn't supposed to be specific to OpenMM in any way.  It's just a generally useful collection of data for people to train models on.

**Comment by peastman** [comment]
I renamed it to `spice-dataset`.  Github will still accept `qmdataset` as a synonym, but it would be best to update all your references to it.
