### ISSUE TITLE
What element coverage does the SPICE dataset provide?

### ISSUE THREAD

**Issue by jchodera** [openmm/spice-dataset#17]
What element coverage does the current set of SPICE datasets provide?

Could we add to the README more info about level of theory, elements, etc?

**Comment by pavankum** [comment]
Each of the spice datasets [here](https://github.com/openforcefield/qca-dataset-submission#basic-datasets) have the elements coverage and other metadata on their landing page (copied that here), do you prefer to have the same in a list like below?

|||||
|-|-|-|-|
| `SPICE DES Monomers Single Points Dataset v1.1` | [2021-11-15-QMDataset-DES-monomers-single-points](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2021-11-15-QMDataset-DES-monomers-single-points ) | Single point energy calculation of DES monomers. | I, C, Br, P, Cl, H, S, O, F, N | [![Complete](https://img.shields.io/badge/Status-Complete-brightgreen)](https://img.shields.io/badge/Status-Complete-green) |
| `SPICE Solvated Amino Acids Single Points Dataset v1.1` | [2021-11-08-QMDataset-Solvated-Amino-Acids-single-points]( https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2021-11-08-QMDataset-Solvated-Amino-Acids-single-points )  | Single point energy calculation of solvated amino acids. | N, S, O, C, H | [![Complete](https://img.shields.io/badge/Status-Complete-brightgreen)](https://img.shields.io/badge/Status-Complete-green) |
| `SPICE DES370K Single Points Dataset v1.0` | [2021-11-08-QMDataset-DES370K-single-points]( https://github.com//openforcefield/qca-dataset-submission/tree/master/submissions/2021-11-08-QMDataset-DES370K-single-points ) | SPICE single point dataset for ML applications. | 'N', 'O', 'Mg', 'H', 'F', 'K', 'Br', 'Na', 'P', 'Cl', 'I', 'Ca', 'S', 'Li', 'C' | [![Complete](https://img.shields.io/badge/Status-Complete-brightgreen)](https://img.shields.io/badge/Status-Complete-green) |
| `SPICE DES370K Single Points Dataset Supplement v1.0` | [2022-02-18-QMDataset-DES370K-single-points-supplement]( https://github.com//openforcefield/qca-dataset-submission/tree/master/submissions/2022-02-18-QMDataset-DES370K-single-points-supplement ) | SPICE single point dataset for ML applications. | F, H, Cl, S, I, Br, N, Li, O, C, Na | [![Running](https://img.shields.io/badge/Status-Running-orange)](https://img.shields.io/badge/Status-Running-orange) |
| `SPICE Dipeptides Single Points Dataset v1.2` | [2021-11-08-QMDataset-Dipeptide-single-points]( https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2021-11-08-QMDataset-Dipeptide-single-points )  | SPICE single point dataset for ML applications. | C ,N ,O ,H ,S  | [![Complete](https://img.shields.io/badge/Status-Complete-brightgreen)](https://img.shields.io/badge/Status-Complete-green)  |
| `SPICE PubChem Set 1 Single Points Dataset v1.2` | [2021-11-08-QMDataset-pubchem-set1-single-points]( https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2021-11-08-QMDataset-pubchem-set1-single-points )  | SPICE single point dataset for ML applications. | 'O', 'Cl', 'N', 'C', 'P', 'Br', 'S', 'F', 'I', 'H' | [![Running](https://img.shields.io/badge/Status-Running-orange)](https://img.shields.io/badge/Status-Running-orange)  |
| `SPICE PubChem Set 2 Single Points Dataset v1.2` | [2021-11-09-QMDataset-pubchem-set2-single-points]( https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2021-11-09-QMDataset-pubchem-set2-single-points )  | SPICE single point dataset for ML applications. | 'H', 'P', 'C', 'Cl', 'Br', 'N', 'F', 'S', 'O', 'I' | [![Running](https://img.shields.io/badge/Status-Running-orange)](https://img.shields.io/badge/Status-Running-orange)  |
| `SPICE PubChem Set 3 Single Points Dataset v1.2` | [2021-11-09-QMDataset-pubchem-set3-single-points]( https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2021-11-09-QMDataset-pubchem-set3-single-points )  | SPICE single point dataset for ML applications. | 'N', 'C', 'S', 'Cl', 'Br', 'F', 'P', 'I', 'H', 'O' | [![Running](https://img.shields.io/badge/Status-Running-orange)](https://img.shields.io/badge/Status-Running-orange)  |
| `SPICE PubChem Set 4 Single Points Dataset v1.2` | [2021-11-09-QMDataset-pubchem-set4-single-points]( https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2021-11-09-QMDataset-pubchem-set4-single-points )  | SPICE single point dataset for ML applications. | 'N', 'S', 'Br', 'O', 'C', 'F', 'H', 'I', 'Cl', 'P' | [![Running](https://img.shields.io/badge/Status-Running-orange)](https://img.shields.io/badge/Status-Running-orange)  |
| `SPICE PubChem Set 5 Single Points Dataset v1.2` | [2021-11-09-QMDataset-pubchem-set5-single-points]( https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2021-11-09-QMDataset-pubchem-set5-single-points )  | SPICE single point dataset for ML applications. | 'F', 'H', 'S', 'Br', 'Cl', 'N', 'P', 'C', 'I', 'O' | [![Running](https://img.shields.io/badge/Status-Running-orange)](https://img.shields.io/badge/Status-Running-orange)  |
| `SPICE PubChem Set 6 Single Points Dataset v1.2` | [2021-11-09-QMDataset-pubchem-set6-single-points]( https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2021-11-09-QMDataset-pubchem-set6-single-points )  | SPICE single point dataset for ML applications. | 'Cl', 'O', 'N', 'H', 'C', 'P', 'S', 'F', 'Br', 'I' | [![Running](https://img.shields.io/badge/Status-Running-orange)](https://img.shields.io/badge/Status-Running-orange)  |

**Comment by jchodera** [comment]
@pavankum : This is great! Would you mind adding this to the [main `README.md`](https://github.com/openmm/spice-dataset/blob/main/README.md)?

**Comment by peastman** [comment]
I have stats on coverage for the version 1.0 dataset.  This table lists element, formal charge, and the total number of times each one occurs in the dataset.  I'm including it in the paper.

|Element|Charge|Instances|
|---|---|---|
|Br|-1|4276
|Br|0|87927
|C|-1|5899
|C|0|12545137
|C|1|1800
|Ca|2|1587
|Cl|-1|7622
|Cl|0|246165
|F|-1|4033
|F|0|376898
|H|0|1594
|I|-1|4344
|I|0|21908
|K|1|6704
|Li|1|3531
|Mg|2|1488
|N|-1|11642
|N|0|2231039
|N|1|114621
|Na|1|6536
|O|-1|81548
|O|0|2235856
|O|1|1500
|P|0|41528
|P|1|750
|S|-1|3350
|S|0|512526
|S|1|3945

**Comment by jchodera** [comment]
This is now described in the [README.md](https://github.com/openmm/spice-dataset/blob/main/README.md).
