### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by jchodera** [openmm/spice-dataset#34]
It would be useful if the [README.md](https://github.com/openmm/spice-dataset/blob/main/README.md) contained information on
* The purpose of the dataset
* What the dataset contains
* What units it uses
* How to download it
* How to cite it
* How it was generated
* Any filtering that has been done in preparing this dataset
* How to access the data directly on QCArchive
* How to prepare new HDF5 files by downloading it yourself
* Who contributed

**Comment by peastman** [comment]
This is one of the next items on my to-do list.

**Comment by jchodera** [comment]
This was handled in #20 .
