### ISSUE TITLE
File format for molecules and conformations

### ISSUE THREAD

**Issue by peastman** [openmm/spice-dataset#4]
What file format or formats are best for the input conformations?  Does QCFractal have specific requirements, or is any reasonable format acceptable?

If we don't have specific requirements, I can make a few suggestions.  For peptides and amino acids, PDB or PDBx/mmCIF would be the obvious choices.  For other molecules, SDF or mol2 would be the standard ones.  Because there will be 50 conformations for each molecule, I suggest splitting the data into two files.  First, have a PDB/SDF/mol2 file with just a single conformation.  This will document the molecular topology.  Pair it with a DCD file containing the coordinates for all 50 conformations.  That will use far less disk space than storing all the conformations in one of the text based formats.

**Comment by jchodera** [comment]
@simonboothroyd can correct me if I get the details wrong, but because we will use the OpenFF infrastructure, we will want:
1. A list of all molecules in canonical explicit-hydrogen isomeric tagged SMILES, which can be generated using [CMILES](https://cmiles.readthedocs.io/en/latest/). Each atom in the SMILES string is tagged with its index, thus defining both the molecule in a portable, compact manner and the topology.
2. An SDF file containing all the conformers of interest. Whether we want one molecule or multiple molecules will depend on what QCSubmit can handle in order to correctly compress the conformers for each molecule.

**Comment by jchodera** [comment]
Also, you should use the [openff toolkit](https://open-forcefield-toolkit.readthedocs.io/) to generate these. It's quite easy to manipulate molecules and retrieve/export these representations using either the default (RDKit) backend or the OpenEye Toolkit backend if you have it installed.

**Comment by peastman** [comment]
> A list of all molecules in canonical explicit-hydrogen isomeric tagged SMILES

What format do you want this in?  A text file with one row for each molecule?  How do we handle clusters containing multiple molecules?

**Comment by jchodera** [comment]
@simonboothroyd and @jthorton can clarify, but I imagine that we may want a convention like
```
uniquename1 SMILES1
uniquename2 SMILES2
```
and then name each conformer in the SDF with titles like `uniquename1-000`, `uniquename1-001`, etc.

But @jthorton will have a much better idea of what format can easily be ingested at this point.

**Comment by peastman** [comment]
If a separate file for each conformation is required I guess we can do that.  But we're talking about millions of conformations total.  That will pretty much kill the filesystem of any computer you try to store it on.  If we can combine all the conformations for each molecule into a single file, that will help a bit.  If we can put the conformations into a compact binary format like DCD and use the SDF just to define the molecular topology, that will be much better.

Another option would be to put all the files for each collection into a single zip file.

**Comment by jchodera** [comment]
> If a separate file for each conformation is required I guess we can do that. But we're talking about millions of conformations total. That will pretty much kill the filesystem of any computer you try to store it on. If we can combine all the conformations for each molecule into a single file, that will help a bit. If we can put the conformations into a compact binary format like DCD and use the SDF just to define the molecular topology, that will be much better.

I'll let @simonboothroyd @jthorton chime in at this point, but I was suggesting combining bundles of conformations and molecules into single SDF files.

There are certainly more compressed formats that can be used. @bennybp might have some suggestions, since he has produced the downloadable artifacts for the [MolSSI Machine Learning Datasets](https://qcarchive.molssi.org/apps/ml_datasets/) page. I believe these might be HDF5 files, which could in principle store each molecule as an object that represents a matrix of dimension `nsnapshots x natoms x ndim` with attributes attached to each object to identify the molecule, its tagged SMILES, etc. A format like this could probably be easily supported by [QCSubmit](https://github.com/openforcefield/openff-qcsubmit) with a little work.

**Comment by peastman** [comment]
HDF5 would work nicely.  It could have one group for each molecule, containing the fields `smiles` for the SMILES string, `sdf` with the topology in SDF format, and `coordinates` with the matrix of coordinates for all conformations.

**Comment by jthorton** [comment]
QCSubmit currently supports any file format that the openff toolkit can read and openff toolkit Molecule objects, so if you want to supply the conformers this would need to be SDF or PDB (provided you have openeye). If however, you want to generate the conformers from within the toolkit you could start with simple smiles strings in the format @jchodera suggested above don't worry too much about making the tagged CMILES QCSubmit will make this automatically for you. 

If we do have to have a separate conformation for every molecule in a different file QCSubmit will deduplicate these once it has read them based on the fixed hydrogen inchikey so the topology must match. 

The largest dataset we have prepared so far can be found [here](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2021-03-30-OpenFF-Industry-Benchmark-Season-1-v1.0) which consisted of around 70K optimizations I imagine a submission folder with this layout would be best here as well in terms of preparation and once compressed should not be too large. 

One possible issue is the size of the dataset during submission, at 70K optimizations, QCFractal started to struggle to create the individual QM tasks needed within our 6 hour submission time limit on github actions. You can imagine for a dataset of millions of data points this will take considerably longer @bennybp will know more and how best to get around this. One option would be to create smaller datasets grouped in some way that can then be combined by the user. Note QCSubmit now allows users to combine and filter multiple datasets into their own unique dataset.

**Comment by SimonBoothroyd** [comment]
> I'll let @SimonBoothroyd @jthorton chime in at this point, but I was suggesting combining bundles of conformations and molecules into single SDF files.

+ 1 for this - having single GZipped SDF file (or several with 100000s molecules + conformers per file depending on how we parallelise the generation) that stores the CMILES in an SD tag (if at all) should be a fine strategy and allow us to handle the submission using OFF infrastructure with maybe a bit of raw RDKit to stream the molecules from the file rather than load them all up front.

> One possible issue is the size of the dataset during submission, at 70K optimizations,

cc @dotsdl also

**Comment by peastman** [comment]
Let's tentatively plan on HDF5.  That seems like a really good solution.

Does the SDF need to already have the atoms in canonical order or will QCSubmit take care of reordering?  I'll initially be generating the molecules and conformations in a variety of ways.  For example, I'm currently working on the dipeptides.  I use PDBFixer to generate them and run MD in OpenMM to sample conformations.  That means the atoms are ordered by residue.  But if necessary, I can easily create a RDKit Mol object with embedded conformations and use it to reorder them before writing the SDF and coordinates.

**Comment by jchodera** [comment]
> Let's tentatively plan on HDF5. That seems like a really good solution.

It would be useful to carefully define the spec for these HDF5 files so that it will be easy to add support for them and preserve all the provenance information we need. It might be good to align this with the structure @bennybp uses for archiving the results in HDF5.

**Comment by jchodera** [comment]
> Does the SDF need to already have the atoms in canonical order or will QCSubmit take care of reordering? I'll initially be generating the molecules and conformations in a variety of ways. For example, I'm currently working on the dipeptides. I use PDBFixer to generate them and run MD in OpenMM to sample conformations. That means the atoms are ordered by residue. But if necessary, I can easily create a RDKit Mol object with embedded conformations and use it to reorder them before writing the SDF and coordinates.

In general, it's problematic to mangle atom ordering. SDF does not store atom names, so fixing atom ordering requires solving a graph correspondence problem, which can get very expensive.

>  For example, I'm currently working on the dipeptides. I use PDBFixer to generate them and run MD in OpenMM to sample conformations. 

We can provide you with a very simple way to do this if you're using the OpenFF force field: Construct modular SMILES strings for peptides, and then use `Molecule.from_smiles(smiles)` to create the molecule:
```python
# Construct SMILES for ACE - ALA - NME
smiles = 'CC(=O)' + 'N[C@@H](C)C(=O)' + 'NC'
from openff.toolkit.topology import Molecule
molecule = Molecule.from_smiles(smiles)
molecule.to_file('molecule.sdf', file_format='sdf')
```
The one difficulty is that there is no amino acid residue perception right now in converting from OpenFF `Molecule` -> OpenFF `Topology` -> OpenMM `Topology` objects yet, though this is actively in development, so it's harder to produce an openMM `Topology` object that partitions amino acids into different residues to assign residue template based force field parameters.

**Comment by peastman** [comment]
I'm using CHARMM36.  Don't worry about it.  I can reorder the atoms before writing out the SDF and coordinates.

**Comment by peastman** [comment]
What about complexes of multiple molecules, such as dimers and solvated amino acids?  How will they fit into this system?  For example, is there any way to represent multiple molecules in a single SMILES string?  Should the SDF file contain a separate entry for each molecule, or combine them all into a single entry?

**Comment by peastman** [comment]
Entries in HDF5 files are always arrays.  That is, you can't store a string, only an array of strings.  So the simplest answer might be that the `smiles` and `sdf` entries have length equal to the number of molecules in the complex.

**Comment by jchodera** [comment]
> Entries in HDF5 files are always arrays. That is, you can't store a string, only an array of strings. So the simplest answer might be that the smiles and sdf entries have length equal to the number of molecules in the complex.

HDF5 supports 
* [Groups](https://docs.h5py.org/en/stable/high/group.html), which function like directories. We might want to use these to organize things.
* [Datasets](https://docs.h5py.org/en/stable/high/dataset.html), which function like numpy arrays. We would likely want one dataset object per molecule, of dimension `(n_snapshots, n_atoms, n_dims)`
* [Attributes](https://docs.h5py.org/en/stable/high/attr.html) that label the datasets. We can use these to label each molecule dataset with the canonical isomeric tagged SMILES for the molecule, and potentially other useful metadata, like a molecule name or description. We can also use attributes to specify the units for datasets (e.g. "angstroms") since HDF5 is intended to use these as part of its self-documenting dataset features.

**Comment by peastman** [comment]
But as noted above, we sometimes need multiple SMILES strings and multiple SDF topologies.  Unless you have a better suggestion for how to handle complexes?

**Comment by jchodera** [comment]
[SMILES](http://opensmiles.org/opensmiles.html) uses the `.` to separate disconnected components. You can still tag each atom in the canonical isomeric explicit hydrogen SMILES to denote which atom in the HDF5 array corresponds to which atom in the SMILES chemical topology, even if there are multiple disconnected components in the SMILES.

There are may be challenges using QCSubmit for separated components, however---our metadata generation scheme currently expects single molecules, I think.

**Comment by peastman** [comment]
@SimonBoothroyd @jthorton can you propose a structure for the HDF5 file?  Whatever will make it easiest for you to work with it.

**Comment by peastman** [comment]
Any feedback on the file structure?  We can stick with what's in #5, or I can easily change it to something else if that will be more convenient for you.

**Comment by jthorton** [comment]
@peastman thanks for the mock file I think this format looks great and is nice and simple. Some feedback:
- we can use either the SDF block or the mapped canonical isomeric smiles to get the molecule topology, I think the mapped smiles is better as this is more compact. 
- The mapped smiles must have all atoms explicitly defined the two you provided contain implicit hydrogens and so they could not be used in testing.
- QCSubmit will not reorder the molecules and will respect the order you enter them in.
- We should include the units for the conformations using the keywords like `f["ALA-ALA"]["conformations"].attrs["units"]`
- For entries with multiple molecules (water clusters etc) it would be easier for QCSubmit to take a list of mapped smiles strings one for each molecule and then a list of conformer arrays.

Would you like to regenerate this file following these steps so I can have a go at feeding into QCSubmit?

**Comment by peastman** [comment]
Thank you!  I'll make those changes and post an updated version.  To clarify one point,

> we can use either the SDF block or the mapped canonical isomeric smiles to get the molecule topology, I think the mapped smiles is better as this is more compact.

Should I still include both SMILES and SDF in the file?  Or are you saying the SDF isn't needed?  Assuming we do include it, should we have a separate SDF block for each molecule like with the SMILES strings, or should there be a single SDF block containing all molecules?

**Comment by SimonBoothroyd** [comment]
> Should I still include both SMILES and SDF in the file? Or are you saying the SDF isn't needed?

So long as we have the fully mapped smiles with explicit hydrogens we shouldn't need the SDF so you can exclude that!

**Comment by peastman** [comment]
A question about how to generate the SMILES strings when there are multiple molecules.  Do the atom indices refer to the order within each molecule, or within the whole complex?  If there are 20 water molecules, does each have an identical SMILES string tagging the atoms as 1, 2, and 3?  Or does each have a different string with different indices?

**Comment by jchodera** [comment]
Good question. The purpose of the SMILES strings tagged with atom indices is to identify which atom is which in a `Topology` equivalent representation for the whole system, so I'd suggest these have to be unique for the entire system and correspond to the ordering within the Topology.

What I can't quite recall is whether we start with 0 or 1 indexing.

The standard way to represent a multicomponent system with SMILES is to separate the SMILES for each molecule with a `.`, as in `CC1=C(C=C(C=C1)NC(=O)C2=CC=C(C=C2)CN3CCN(CC3)C)NC4=NC=CC(=N4)C5=CN=CC=C5.CS(=O)(=O)O` for [imatinib mesylate](https://pubchem.ncbi.nlm.nih.gov/compound/Imatinib-mesylate) (the sulfate salt of imatinib).

**Comment by peastman** [comment]
Right, but @jthorton [said above](https://github.com/openmm/qmdataset/issues/4#issuecomment-916064312) it would be easier for QCSubmit to have an array of independent SMILES strings, one for each molecule.

**Comment by jthorton** [comment]
@peastman good question as we are considering each smiles string as a separate molecule the atom indices refer to the order within each molecule starting from an index of 1. So for 20 water molecules, each would have identical SMILES. Again if you would like to make a test HDF5 file for me to test that would be great!

**Comment by jchodera** [comment]
There should at least be *some* SMILES that indicates the tagged atom
topology for the entire system, but there could be multiple representations
attached for convenience.

For uploading an HDF5 file: if you cut a release, you can attach an HDF5 as
a release artifact.

**Comment by jthorton** [comment]
I have been playing around with this some more and I actually think it might be easier If we have one SMILES string that encodes the system as @jchodera  pointed out indexed from 1 and have no repeated indices and a single position array per confirmation should be supplied. This should be easier as we then don't have to split up the positions from openMM into per molecule arrays. 

I have tested the tookit functions we need and they work better than I thought they would with the multicomponent systems so could we try a HDF5 file with this format @peastman?

**Comment by peastman** [comment]
Ok, I can do that.  I'm currently working on the script for solvated amino acids.  Here's an example of a SMILES string for an alanine with 20 waters.  Does this look ok?

```
[O:10]([H:45])[H:46].[O:11]([H:47])[H:48].[O:12]([H:49])[H:50].[O:13]([H:51])[H:52].[O:14]([H:53])[H:54].[O:15]([H:55])[H:56].[O:16]([H:57])[H:58].[O:17]([H:59])[H:60].[O:18]([H:61])[H:62].[O:19]([H:63])[H:64].[O:1]=[C:23]([N:26]([C@@:30]([C:24](=[O:2])[N:25]([C:28]([H:76])([H:77])[H:78])[H:71])([C:29]([H:79])([H:80])[H:81])[H:82])[H:72])[C:27]([H:73])([H:74])[H:75].[O:20]([H:65])[H:66].[O:21]([H:67])[H:68].[O:22]([H:69])[H:70].[O:3]([H:31])[H:32].[O:4]([H:33])[H:34].[O:5]([H:35])[H:36].[O:6]([H:37])[H:38].[O:7]([H:39])[H:40].[O:8]([H:41])[H:42].[O:9]([H:43])[H:44]
```

**Comment by jthorton** [comment]
Yeah, that looks great, I was able to build a molecule from it and detect the 21 subgraphs in the topology.

**Comment by jchodera** [comment]
We use the [`Topology`](https://open-forcefield-toolkit.readthedocs.io/en/0.10.0/topology.html) object to represent systems containing multiple molecules. It's probably a good idea to extend `Topology` with a `.to_smiles()` method that does this in a canonical way rather than try to abuse `Molecule` to contain multiple molecules---a task for which it is not intended.

@peastman : The QCFractal/QCArchive infrastructure was not built with multiple-molecule systems in mind, so I'd suggest splitting this into two datasets: A single-molecule-in-vacuum dataset (which should work fine) and a solvated-molecules dataset (which is likely to run into sharp edges) and submit them separately.

**Comment by peastman** [comment]
The above question was for the DES370K dataset.  They identify each sample by the SMILES strings of the two monomers, not in canonical order and with implicit hydrogens.  Then they give a list of atomic coordinates, but it's ambiguous which atom each coordinate refers to.  So I also have a SDF file for each monomer, with all atoms explicit and with the same order used for the coordinates.  To create a sample I need to load the two SDF files, associate the correct coordinates with each atom, canonical order them, and generate a combined SMILES string.

> The QCFractal/QCArchive infrastructure was not built with multiple-molecule systems in mind

We'll need to get that working before we can create this dataset.

**Comment by jthorton** [comment]
@jchodera @peastman I have drafted a [PR](https://github.com/openforcefield/openff-toolkit/pull/1086) to the toolkit which would allow users to generate a single SMILES string for a multi-component topology.  Attached is a code snipit which should allow you to do this starting from an SDF file.

```python
from openff.toolkit.topology import Molecule, Topology
# load the SDF files of the molecules
mol1 = Molecule.from_file("file1.sdf")
mol2 = Molecule.from_file("file2.sdf")
# optionally put molecules in canonical order 
mol1 = mol1.canonical_order_atoms()
mol2 = mol2.canonical_order_atoms()

top = Topology.from_molecules([mol1, mol2])
top.to_smiles(mapped=True)
```
Note the coordinates are also remapped when using the `canonical_order_atoms` method. 

> The QCFractal/QCArchive infrastructure was not built with multiple-molecule systems in mind

It is possible to run multi-molecule calculations as there are some [reaction datasets](https://qcarchivetutorials.readthedocs.io/en/latest/basic_examples/reaction_datasets.html#Reaction-Datasets) now in QCArchive. This will however be our first time submitting multi-molecule systems and so I would suggest a small test submission first.

**Comment by peastman** [comment]
That looks perfect, thanks!

> This will however be our first time submitting multi-molecule systems and so I would suggest a small test submission first.

The solvated amino acids will be a good test case.  It's only 26 clusters, 1300 conformations total.

**Comment by peastman** [comment]
Closing since version 1 is now released.
