### ISSUE TITLE
MBIS valence widths

### ISSUE THREAD

**Issue by JoshRackers** [openmm/spice-dataset#61]
Would it be possible to add MBIS valence widths to the dataset? I know psi4 computes these automatically when an MBIS calculation is done.

**Comment by peastman** [comment]
Yes, it looks like that information is present in QCArchive.  You can use the [downloader script](https://github.com/openmm/spice-dataset/tree/main/downloader) to get a copy of the dataset including it.  Just edit config.yaml and add `'MBIS VALENCE WIDTHS'` to the list of values.

**Comment by JoshRackers** [comment]
Excellent! I will give this a try.

**Comment by JoshRackers** [comment]
I don't suppose the whole density matrix was saved to QCArchive?

**Comment by peastman** [comment]
No, that would have taken way more storage than they had!

**Comment by JoshRackers** [comment]
I figured that might be the case! Thanks!
