### ISSUE TITLE
Dataset for new batch of molecular structures

### ISSUE THREAD

**Issue by JoshRackers** [openmm/spice-dataset#62]
I have a small batch of molecular structures that I would like to run through the psi4 protocol here (no MD or relaxation needed), so that I can generate a new dataset in the same format as the rest of SPICE. Is there a script around to do that? I have the structures in one extended xyz file.

**Comment by pavankum** [comment]
Hi @JoshRackers, [here is one dataset submission directory](https://github.com/openforcefield/qca-dataset-submission/tree/master/submissions/2021-11-15-QMDataset-DES-monomers-single-points) on how the input hdf5 file was processed using [openff-qcsubmit](https://github.com/openforcefield/openff-qcsubmit) and computed using [qcfractal](https://github.com/MolSSI/QCFractal) server hosted by MolSSI (you can set up your own server, some tutorials [here](https://github.com/pavankum/blogpost/blob/main/Step3_dataset_submission_on_cluster.ipynb)).

**Comment by JoshRackers** [comment]
Thanks! Let me make sure I have this correct:

1. I run a version of the Jupyter notebook from your first link to produce a "dataset" like this: [https://github.com/openforcefield/qca-dataset-submission/blob/master/submissions/2021-11-15-QMDataset-DES-monomers-single-points/dataset.json.bz2]  In this example, I see that the molecule structures are read in in an hdf5 file. Is this the only file type supported?
2. I submit that that "dataset" file to a qcfractal server. I can do this either on my own server if I set up qcfractal there or submit directly to the MOLSSI resource.

Is that right?

**Comment by pavankum** [comment]
> Is this the only file type supported?

It can take smiles, or sdf files, or openff molecules as well.

> I submit that that "dataset" file to a qcfractal server. I can do this either on my own server if I set up qcfractal there or submit directly to the MOLSSI resource.

Yeah, that's right. To submit to MolSSI server you may need credentials (tagging @bennybp @dotsdl), and compute managers to do the calculations.

If you are not calculating in 1000's then another easy way is to parallelize a qcengine compute energy call with dask or multiprocessing, here is a single point energy calculation
```
from qcelemental.models import AtomicInput, Molecule, DriverEnum
from qcelemental.models.common_models import Model
from qcengine import compute

def main():
    qcmol = Molecule.from_data(
        """
    0 1
    H            0.856507560196     0.771327307016     0.559729319002
    O            0.121036132436     0.684379466849    -0.035268035646
    O           -0.121036132436    -0.684379466849    -0.035268035646
    H           -0.856507560196    -0.771327307016     0.559729319002
    """
    )

    print(qcmol)
    result = compute(
        input_data=AtomicInput(
            molecule=qcmol,
            driver=DriverEnum.gradient,
            model=Model(
                method="wb97m-d3bj",
                basis="def2-tzvppd",
                keywords={
                    "wcombine": False,
                    "implicit_solvent": "null",
                    "store_wavefunction": "none",
                    "maxiter": 200,
                    "scf_properties": [
                        "dipole",
                        "quadrupole",
                        "wiberg_lowdin_indices",
                        "mayer_indices",
                        "mbis_charges",
                    ],
                },
            ),
        ),
        program="psi4",
        local_options={"ncores": 8, "jobs_per_node": 1, "scratch_directory": "/tmp/"},
    )
    breakpoint()
    print("Energy:", result.properties.scf_total_energy)
    print("Gradient:", result.properties.scf_total_gradient)
    print("Dipole moment:", result.properties.scf_dipole_moment)

if __name__ == "__main__":
    main()
```
I think [from_string() can take xyz](https://github.com/MolSSI/QCElemental/blob/86b4700dacc6322998d8580b352f1d27cde33962/qcelemental/molparse/from_string.py#L36) as well. I didn't get all the `scf_properties` I asked it to calculate, might be something wrong there, other than that this should work.

**Comment by peastman** [comment]
It would be good to add this to the documentation.  A few people have told me they'd like to generate their own data to use along with SPICE.  For example, could we provide a Psi4 input file that shows exactly what settings to use?

**Comment by leeping** [comment]
I agree that providing an input file template would really be helpful.  For running the single point calculations, the template would actually be sufficient because there's many ways to execute Psi4 in an embarrassingly parallel way; @pavankum had a great suggestion but I also like to use Work Queue for parallelization.

Also, I think that if the script for generating the structures could be shared, it would be helpful for future contributors to generate data that has more consistency with as what's already in SPICE.  In terms of the quality of the final fitted potential, I think the procedure for generating structures has a huge impact and may be as important as choosing the right level of theory.

**Comment by pavankum** [comment]
Here is a sample template for psi4 
```
memory 180 gb
psi4_io.set_default_path("/tmp")


molecule sample{
0 1
S    2.14115412    3.34483413    5.83118474
S    3.93694189    2.43268204    2.54786115
C    0.25443274    6.03087160    4.89660178
C    6.63161588    4.52659328    2.59640792
H   -0.85733096    6.62095777    6.5580485
H   -1.06142141    5.53854171    3.35689051
H    1.42978575    7.63740400    4.27843445
H    6.06683372    6.53232955    2.5450074
H    7.81091820    4.21108460    4.28587972
H    7.77333187    4.11376355    0.90211747
--
1 1
Li   1.41761583   -6.70427585    5.96771769
units bohr
symmetry c1
noreorient
nocom
}

set {
 wcombine false
 }

props = ['DIPOLE', 'QUADRUPOLE', 'WIBERG_LOWDIN_INDICES', 'MAYER_INDICES']
gradient('wB97M-D3(BJ)/def2-TZVPPD', properties=props)
clean()
```

Equivalent input via qcengine

```
import numpy as np
import psi4
import json

json_data = {'driver': 'gradient',
 'extras': {'_qcfractal_tags': {'keywords': '32', 'program': 'psi4'}},
 'id': '100346221',
 'keywords': {'maxiter': 200,
              'scf_properties': ['dipole', 'quadrupole', 'wiberg_lowdin_indices', 'mayer_indices'],
              'wcombine': False},
 'model': {'basis': 'def2-tzvppd', 'method': 'wb97m-d3bj'},
 'molecule': {'connectivity': [[0, 1, 1.0], [0, 2, 1.0], [1, 3, 1.0], [2, 4, 1.0], [2, 5, 1.0], [2, 6, 1.0],
                               [3, 7, 1.0], [3, 8, 1.0], [3, 9, 1.0]],
              'extras': {'canonical_isomeric_explicit_hydrogen_mapped_smiles': '[H:5][C:3]([H:6])([H:7])[S:1][S:2][C:4]([H:8])([H:9])[H:10].[Li+:11]'},
              'fix_com': True,
              'fix_orientation': True,
              'fix_symmetry': 'c1',
              'fragment_charges': [0.0, 1.0],
              'fragments': [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10]],
              'geometry': [2.14115412, 3.34483413, 5.83118474, 3.93694189, 2.43268204, 2.54786115, 0.25443274,
                           6.0308716, 4.89660178, 6.63161588, 4.52659328, 2.59640792, -0.85733096, 6.62095777,
                           6.5580485, -1.06142141, 5.53854171, 3.35689051, 1.42978575, 7.637404, 4.27843445, 6.06683372,
                           6.53232955, 2.5450074, 7.8109182, 4.2110846, 4.28587972, 7.77333187, 4.11376355, 0.90211747,
                           1.41761583, -6.70427585, 5.96771769],
              'id': '91096659',
              'identifiers': {'molecular_formula': 'C2H6LiS2',
                              'molecule_hash': '2481d82ffb6de16461d032bbe6355ee2fbe13dc8'},
              'molecular_charge': 1.0,
              'molecular_multiplicity': 1,
              'name': 'C2H6LiS2',
              'provenance': {'creator': 'QCElemental',
                             'routine': 'qcelemental.molparse.from_schema',
                             'version': 'v0.22.0'},
              'schema_name': 'qcschema_molecule',
              'schema_version': 2,
              'symbols': ['S', 'S', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'Li'],
              'validated': True},
 'protocols': {'wavefunction': 'none'},
 'provenance': {'creator': 'QCElemental', 'routine': 'qcelemental.models.results', 'version': 'v0.24.0'},
 'schema_name': 'qcschema_input',
 'schema_version': 1}

psi4.set_num_threads(40)
psi4.set_memory('180 GB')
json_ret = psi4.schema_wrapper.run_qcschema(json_data)
print(json_ret.stdout)
with open('output_'+json_data['id']+'.out', 'w') as f:
    f.write(json_ret.stdout)
```

**Comment by peastman** [comment]
All the scripts used to generate conformations are in this repository.  For example, [here is the script](https://github.com/openmm/spice-dataset/blob/main/pubchem/createPubchem.py) for PubChem molecules.

@pavankum thanks for the example files.  I'll put together some documentation based on them.
