### ISSUE TITLE
Unit of the observables

### ISSUE THREAD

**Issue by rhythmswing** [openmm/spice-dataset#83]
Hi,

I wonder what are the units for the observables in the dataset? Particularly, I'm interested in the units of energies and forces, including all formation energies, total energies, forces (negative gradients), and the positions. 

Thank you, much appreciated.

**Comment by peastman** [comment]
Everything is in atomic units.  Energies are in hartree and distances are in bohr.  That means forces are in hartree/bohr.  The units are described on the Zenodo page, and also annotated in the HDF5 file.

**Comment by rhythmswing** [comment]
> Everything is in atomic units. Energies are in hartree and distances are in bohr. That means forces are in hartree/bohr. The units are described on the Zenodo page, and also annotated in the HDF5 file.

Thank you! 
Am I correct that in order to convert positions to Angstrom they are multiplied by 0.52 roughly, and for forces to eV/A they are multiplied by something like 27 / 0.52? 

Furthermore, this might be a separate issue, but I see some groups  in which some samples have disproportionally large force components compared to the rest of the samples. Is this normal or due to perhaps data contamination? Thank you!

Here's an example to what I'm talking about: https://streamable.com/vgqjke
the link contains a video to a visualization of ID 104029936, and I converted the units to eV/A with the conversion I said above. The black arrows indicate the force components of each atom. Seems like for some snapshots the forces are disproportionally large.

**Comment by peastman** [comment]
Let's see.

```python
>>> from openmm.unit import *
>>> (1*bohr).value_in_unit(angstrom)
0.529177210903
>>> (1*hartree/bohr).value_in_unit(ev/angstrom)
51.42206747632596
```

Yes, that looks right.

The very large forces are caused by an issue in the version of psi4 we used, where occasionally calculations didn't converge properly.  See #60.  In generating the HDF5 file we applied a filter based on force magnitude to identify and remove those samples.  For SPICE v2 we're planning to rerun those calculations with a newer version of psi4.

**Comment by rhythmswing** [comment]
> Let's see.
> 
> ```python
> >>> from openmm.unit import *
> >>> (1*bohr).value_in_unit(angstrom)
> 0.529177210903
> >>> (1*hartree/bohr).value_in_unit(ev/angstrom)
> 51.42206747632596
> ```
> 
> Yes, that looks right.
> 
> The very large forces are caused by an issue in the version of psi4 we used, where occasionally calculations didn't converge properly. See #60. In generating the HDF5 file we applied a filter based on force magnitude to identify and remove those samples. For SPICE v2 we're planning to rerun those calculations with a newer version of psi4.

Thank you! 
I did my own filter and it would seem like the large forces account for a small fraction of the dataset which doesn't seem to cause a lot of harm to ignore right now. Thanks a lot for the clarifications.
