### ISSUE TITLE
Gradient sign

### ISSUE THREAD

**Issue by nec4** [openmm/spice-dataset#94]
Hello - apologies if this is a silly question:

`dft_total_gradient` -> is this meant to be interpreted as the forces, or literally as dU/dx? Is it necessary to add a negative sign to recover the forces?

**Comment by peastman** [comment]
It's the gradient, meaning the negative of the forces.

**Comment by nec4** [comment]
I see, so a negative sign must be added by the user downstream to do force matching. Thanks!

**Comment by nec4** [comment]
Actually I am confused. When I plot the first entry vectors for the `dft_total_gradient` for the the system `[cl-] [k+]` (two ions of opposite sign), plotting the first example of the raw `dft_total_gradient` vectors (and putting the tails at the respective atom positions) gives the following picture:

![Screen Shot 2024-02-07 at 7 53 32 PM](https://github.com/openmm/spice-dataset/assets/42926839/d57db0f8-d559-4896-8e44-dc2136531edf)

Which is what we would expect from attractive forces between oppositely charged ions in vaccum. So it seems the quantities in `dft_total_gradient` are true forces? Therefore there is no need to manually multiply by -1 in order to train on forces; the `dft_total_gradient` can just be directly loaded and used as the force?

**Comment by peastman** [comment]
[The Psi4 documentation](https://psicode.org/psi4manual/master/glossary_psivariables.html) describes that field as, "The total electronic gradient [E_h/a0] of the requested DFT method."

**Comment by nec4** [comment]
I must be missing a minus sign somewhere. Thanks.
